
import { MenuItem, ExtraOption } from './types';

export const EXTRA_OPTIONS: ExtraOption[] = [
  { id: 'ext1', label: 'Larmes de Truffe Noire du Périgord', price: 18 },
  { id: 'ext2', label: 'Essence de Foie Gras au Porto', price: 9 },
  { id: 'ext3', label: 'Pain de Seigle à l\'Or & Beurre Fumée', price: 7 },
  { id: 'ext4', label: 'Cristaux de Sel de l\'Himalaya & Huile de Myrrhe', price: 4 },
  { id: 'ext5', label: 'Pétales d\'Or 24 Carats (Décoration)', price: 15 },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'L\'Âme des Profondeurs',
    description: 'Carpaccio de bar sauvage disposé en rosace translucide, corail d\'oursin givré, perles de citron caviar et rosée d\'eau de mer.',
    price: 34,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'Ultra-fine slices of raw sea bass arranged in a hypnotic rose pattern on a dark stone plate. Topped with bright orange sea urchin roe, delicate citrus pearls, and micro-herbs. Glistening with sea water vinaigrette. Fine dining art, cinematic macro photography.',
    calories: 185,
    isVegetarian: false,
  },
  {
    id: '2',
    name: 'Le Poids de l\'Héritage',
    description: 'Bloc monolithique de foie gras de canard, voile de gelée au Sauternes, poussière de noisettes torréfiées et fragment d\'or pur.',
    price: 38,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1519623286359-e9f3cbef015b?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A perfect geometric cube of smooth foie gras terrine. Topped with a translucent amber-colored wine jelly veil and a single large flake of real gold leaf. Minimalist architectural plating on a white ceramic disk. Moody studio lighting.',
    calories: 410,
    isVegetarian: false,
  },
  {
    id: '3',
    name: 'Géométrie Sacrée de l\'Agneau',
    description: 'Selle d\'agneau de pré-salé rôtie aux herbes de garrigue, racines oubliées sculptées, jus corsé à l\'infusion de myrrhe.',
    price: 48,
    category: 'Mains',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'Slices of perfectly pink lamb loin arranged in a geometric formation. Accompanied by turned root vegetables and a dark, glossy, mirror-like reduction sauce. Modern plating, clean lines, luxury restaurant setting.',
    calories: 620,
    isVegetarian: false,
  },
  {
    id: '4',
    name: 'Épure de Cabillaud Boréal',
    description: 'Dos de cabillaud nacré à basse température, émulsion vaporeuse au lait d\'amande amère, huile de pin émeraude et neige de raifort.',
    price: 42,
    category: 'Mains',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A thick, perfectly flaky white cod fillet. Surrounded by a light, airy white almond foam and droplets of vibrant green pine oil. Topped with fine white horseradish snow. Abstract white-on-white culinary art.',
    calories: 340,
    isVegetarian: false,
  },
  {
    id: '5',
    name: 'L\'Effondrement Cacaoté',
    description: 'Sphère de chocolat noir 88% en lévitation, cœur fondant au poivre de Tasmanie, dentelle de charbon végétal et sel noir d\'Hawaï.',
    price: 32,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A dark chocolate sphere cracked open to reveal a flowing spicy chocolate center. Intricate black cocoa lace structures surrounding the sphere. Sprinkled with black volcanic salt. Dramatic Chiaroscuro lighting, luxury dessert.',
    calories: 450,
    isVegetarian: true,
  },
  {
    id: '6',
    name: 'Nébuleuse de Fruits Rouges',
    description: 'Meringue soufflée à l\'azote, sorbet intense à l\'hibiscus, nuage de violette et rosée de fraises des bois.',
    price: 28,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A deconstructed berry dessert featuring a vibrant red hibiscus sorbet, light violet-colored foam clouds, and wild strawberries. Plated artistically with negative space and dots of berry gel. Ethereal and colorful fine dining.',
    calories: 220,
    isVegetarian: true,
  },
  {
    id: '7',
    name: 'L\'Or Liquide de Reims',
    description: 'Cuvée de prestige, bulles d\'une finesse infinie, notes de brioche au miel et poussière d\'or en suspension.',
    price: 160,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1594494024039-df300910996c?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A tall crystal flute containing golden vintage champagne. Real gold leaf flakes floating in the bubbles. Dark luxury background with golden light bokeh. Cinematic shot.',
    calories: 120,
    isVegetarian: true,
  },
  {
    id: '8',
    name: 'L\'Élixir de l\'Alchimiste',
    description: 'Cocktail de dégustation : Gin infusé au thé bleu, essence de bergamote, sirop de lune et spray de parfum de rose comestible.',
    price: 26,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A deep blue cocktail in a designer geometric glass. A thin wisp of smoke rising from it. Garnished with a single dried rose petal. Neon amber lighting in a dark high-end bar.',
    calories: 190,
    isVegetarian: true,
  },
  {
    id: '9',
    name: 'Architecture Végétale',
    description: 'Asperges de saison en textures (crues, grillées, en mousseline), jaune d\'œuf confit au soja, voile de truffe d\'été.',
    price: 31,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A complex arrangement of green and white asparagus spears. A central bright yellow soy-cured egg yolk. Shavings of black truffle and micro-greens. Vertical architectural plating, Michelin star style.',
    calories: 230,
    isVegetarian: true,
  },
  {
    id: '10',
    name: 'Le Spectre du Risotto',
    description: 'Riz Vialone Nano infusé au safran pur, moelle de bœuf croustillante, émulsion de réglisse et fleurs de sel de lave.',
    price: 44,
    category: 'Mains',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=800&auto=format&fit=crop',
    generationPrompt: 'A bright yellow saffron risotto in a deep black designer bowl. Topped with dark black licorice foam swirls and black salt crystals. High contrast, luxury food photography.',
    calories: 580,
    isVegetarian: false,
  }
];
